language: node_js
node_js:
  - 6.9.1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - npm install -g yarn

before_script:
  - yarn install

script:
  - yarn test-ci

after_success:
  - yarn coveralls
